"""cliente tables

Revision ID: 30e896eb092d
Revises: 
Create Date: 2026-08-04 11:08:05.547491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e896eb092d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login', sa.VARCHAR(length=70), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('data_nascimento', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('endereco_cliente',
    sa.Column('id_endereco', sa.UUID(), nullable=False),
    sa.Column('apelido', sa.VARCHAR(length=150), nullable=True),
    sa.Column('logradouro', sa.VARCHAR(length=150), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=150), nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=150), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=150), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=150), nullable=False),
    sa.Column('principal', sa.BOOLEAN(), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco_cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
