"""orcamento, avaliacao

Revision ID: 39fc5c74c735
Revises: bb30c8d43822
Create Date: 2026-08-04 14:25:44.305118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39fc5c74c735'
down_revision: Union[str, Sequence[str], None] = 'bb30c8d43822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento',
    sa.Column('id_orcamento', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'CANCELADO', 'EXPIRADO', name='orcamentostatus'), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_validado', sa.DATE(), nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=True),
    sa.Column('id_funcionario', sa.UUID(), nullable=True),
    sa.Column('id_empresa_contrato', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_empresa_contrato'], ['empresa_contrato.id_empresa_contrato'], ondelete='set null'),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id_funcionario'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id_orcamento')
    )
    op.create_table('item_orcamento',
    sa.Column('id_item_orcamento', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_orcamento', sa.UUID(), nullable=False),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamento.id_orcamento'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_orcamento')
    )
    op.create_table('avaliacao',
    sa.Column('id_avaliacao', sa.UUID(), nullable=False),
    sa.Column('nota', sa.INTEGER(), nullable=False),
    sa.Column('comentario', sa.VARCHAR(length=800), nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_pedido', sa.UUID(), nullable=True),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ondelete='set null'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    op.drop_table('item_orcamento')
    op.drop_table('orcamento')
    # ### end Alembic commands ###
