"""funcionarios, fornecedores e produtos

Revision ID: 5c6a7d1b937b
Revises: 30e896eb092d
Create Date: 2026-08-04 11:38:56.778640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c6a7d1b937b'
down_revision: Union[str, Sequence[str], None] = '30e896eb092d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id_funcionario', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login', sa.VARCHAR(length=70), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=20), nullable=False),
    sa.Column('data_nascimento', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('salario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('ADMIN', 'VENDEDOR', 'ESTOQUISTA', 'GESTOR', name='tipofuncionario'), nullable=False),
    sa.Column('comissao_percentual', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    # ### end Alembic commands ###
