"""funcionarios, fornecedores e produtos

Revision ID: 66dfa42917d3
Revises: 5c6a7d1b937b
Create Date: 2026-08-04 11:40:01.949766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66dfa42917d3'
down_revision: Union[str, Sequence[str], None] = '5c6a7d1b937b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedor',
    sa.Column('id_fornecedor', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_fornecedor'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=700), nullable=True),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.INTEGER(), nullable=False),
    sa.Column('tipo_producao', sa.Enum('PRONTO', 'SOB_MEDIDA', name='tipoproducao'), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('fornecedor')
    op.drop_table('categoria')
    # ### end Alembic commands ###
