"""cria tabela movimentacao_estoque

Revision ID: 6bb20b4aa432
Revises: 9d2e4f7a1c3b
Create Date: 2026-08-07 10:57:15.642921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb20b4aa432'
down_revision: Union[str, Sequence[str], None] = '9d2e4f7a1c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao_estoque',
    sa.Column('id_movimentacao', sa.UUID(), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentacao'), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('data_movimentacao', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_reposicao_prevista', sa.DATE(), nullable=True),
    sa.Column('observacao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.Column('id_fornecedor', sa.UUID(), nullable=True),
    sa.Column('id_pedido', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id_fornecedor'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao_estoque')
    # ### end Alembic commands ###
