"""cpf to cpf_cnpj cliente table

Revision ID: 8165ee22f559
Revises: 0d903142d80e
Create Date: 2026-08-11 11:09:14.813139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8165ee22f559'
down_revision: Union[str, Sequence[str], None] = '0d903142d80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf', new_column_name='cpf_cnpj')
    op.create_unique_constraint(op.f('cliente_cpf_cnpj__key'), 'cliente', ['cpf_cnpj'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cliente_cpf_cnpj__key'), 'cliente', type_='unique')
    op.create_unique_constraint(op.f('cliente_cpf_key'), 'cliente', ['cpf'], postgresql_nulls_not_distinct=False)
    op.alter_column('cliente', 'cpf_cnpj', new_column_name='cpf')
    # ### end Alembic commands ###
