"""pedido aceita venda direta para empresa contratante

Revision ID: 84a7ec39fc4c
Revises: c4f3947ab80a
Create Date: 2026-08-07 09:46:26.170406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a7ec39fc4c'
down_revision: Union[str, Sequence[str], None] = 'c4f3947ab80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('id_empresa_contrato', sa.UUID(), nullable=True))
    op.add_column('pedido', sa.Column('id_orcamento', sa.UUID(), nullable=True))
    op.add_column('pedido', sa.Column('endereco_entrega_texto', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('pedido', 'id_cliente',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_pedido_id_orcamento', 'pedido', ['id_orcamento'])
    op.drop_constraint(op.f('pedido_id_cliente_fkey'), 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'cliente', ['id_cliente'], ['id_cliente'], ondelete='set null')
    op.create_foreign_key(None, 'pedido', 'empresa_contrato', ['id_empresa_contrato'], ['id_empresa_contrato'], ondelete='set null')
    op.create_foreign_key(None, 'pedido', 'orcamento', ['id_orcamento'], ['id_orcamento'], ondelete='set null')
    op.create_check_constraint('ck_pedido_cliente_ou_empresa', 'pedido', 'id_cliente IS NOT NULL OR id_empresa_contrato IS NOT NULL')
    op.create_check_constraint('ck_pedido_empresa_requer_funcionario', 'pedido', 'id_empresa_contrato IS NULL OR id_funcionario IS NOT NULL')
    op.create_check_constraint('ck_orcamento_cliente_ou_empresa', 'orcamento', 'id_cliente IS NOT NULL OR id_empresa_contrato IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_orcamento_cliente_ou_empresa', 'orcamento', type_='check')
    op.drop_constraint('ck_pedido_empresa_requer_funcionario', 'pedido', type_='check')
    op.drop_constraint('ck_pedido_cliente_ou_empresa', 'pedido', type_='check')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key(op.f('pedido_id_cliente_fkey'), 'pedido', 'cliente', ['id_cliente'], ['id_cliente'])
    op.drop_constraint('uq_pedido_id_orcamento', 'pedido', type_='unique')
    op.alter_column('pedido', 'id_cliente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pedido', 'endereco_entrega_texto')
    op.drop_column('pedido', 'id_orcamento')
    op.drop_column('pedido', 'id_empresa_contrato')
    # ### end Alembic commands ###
