"""unique func cpf and email

Revision ID: 8a4651f1a29d
Revises: f1e9f6554526
Create Date: 2026-08-06 10:53:33.344593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4651f1a29d'
down_revision: Union[str, Sequence[str], None] = 'f1e9f6554526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'funcionario', ['cpf'])
    op.create_unique_constraint(None, 'funcionario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionario', type_='unique')
    op.drop_constraint(None, 'funcionario', type_='unique')
    # ### end Alembic commands ###
