"""empty message

Revision ID: 95b3fef432a7
Revises: dfd83bafaf2b
Create Date: 2026-09-11 16:25:36.055877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b3fef432a7'
down_revision: Union[str, Sequence[str], None] = 'dfd83bafaf2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionario', 'endereco',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionario', 'endereco',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
