"""pedido

Revision ID: bb30c8d43822
Revises: d720a2d35c86
Create Date: 2026-08-04 14:01:48.759943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb30c8d43822'
down_revision: Union[str, Sequence[str], None] = 'd720a2d35c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_carrinho',
    sa.Column('id_item_carrinho', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_carrinho', sa.UUID(), nullable=False),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id_carrinho'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_carrinho'),
    sa.UniqueConstraint('id_carrinho'),
    sa.UniqueConstraint('id_produto')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'EM_SEPARACAO', 'ENVIADO', 'ENTREGUE', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DEBITO', 'CREDITO', 'DINHEIRO', 'PIX', name='formapagamento'), nullable=False),
    sa.Column('valor_frete', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pedido', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_entrega_prevista', sa.DATE(), nullable=True),
    sa.Column('data_entrega_realizada', sa.DATE(), nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_funcionario', sa.UUID(), nullable=True),
    sa.Column('id_endereco_entrega', sa.UUID(), nullable=True),
    sa.Column('id_carrinho', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id_carrinho'], ondelete='set null'),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_endereco_entrega'], ['endereco_cliente.id_endereco'], ondelete='set null'),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id_funcionario'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('item_pedido',
    sa.Column('id_item_pedido', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_pedido', sa.UUID(), nullable=False),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_pedido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    op.drop_table('item_carrinho')
    # ### end Alembic commands ###
