"""unique fornecedor

Revision ID: c4f3947ab80a
Revises: 8a4651f1a29d
Create Date: 2026-08-06 14:40:59.963096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f3947ab80a'
down_revision: Union[str, Sequence[str], None] = '8a4651f1a29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fornecedor', ['telefone'])
    op.create_unique_constraint(None, 'fornecedor', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fornecedor', type_='unique')
    op.drop_constraint(None, 'fornecedor', type_='unique')
    # ### end Alembic commands ###
