"""carrinho

Revision ID: d720a2d35c86
Revises: 66dfa42917d3
Create Date: 2026-08-04 13:33:13.467849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd720a2d35c86'
down_revision: Union[str, Sequence[str], None] = '66dfa42917d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_contrato',
    sa.Column('id_empresa_contrato', sa.UUID(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('info_contato', sa.VARCHAR(length=150), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('contrato_ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_empresa_contrato'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('carrinho',
    sa.Column('id_carrinho', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'CONVERTIDO', 'ABANDONADO', name='statuscarrinho'), nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_carrinho')
    )
    op.create_table('produto_fornecedor',
    sa.Column('id_produto_fornecedor', sa.UUID(), nullable=False),
    sa.Column('preco_custo', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.Column('id_fornecedor', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id_fornecedor'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_produto_fornecedor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_fornecedor')
    op.drop_table('carrinho')
    op.drop_table('empresa_contrato')
    # ### end Alembic commands ###
