"""image url

Revision ID: dfd83bafaf2b
Revises: ad81a1df2ee4
Create Date: 2026-09-08 13:38:39.731570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd83bafaf2b'
down_revision: Union[str, Sequence[str], None] = 'ad81a1df2ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('imagem_url', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'imagem_url')
    # ### end Alembic commands ###
