"""unique login

Revision ID: f1e9f6554526
Revises: 39fc5c74c735
Create Date: 2026-08-04 15:54:24.960881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e9f6554526'
down_revision: Union[str, Sequence[str], None] = '39fc5c74c735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'funcionario', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionario', type_='unique')
    # ### end Alembic commands ###
